name: "Self hosted runner testing"

on: [pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: List the files in the repository
      run: |
        ls -la
        env
        echo "PR number = ${{ github.event.pull_request.number }}"
